### ISSUE TITLE
Character counter

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#126]
Randy,  How hard would it be to provide a character counter?  I would think we would want to include each word/group space as a character also.  I would like it to stop at either the clicking of STOP or the end of the file and then stay there until the next time PLAY is clicked.

No hurry on this.

Tom

**Comment by RandyLoeb** [comment]
Not hard, but need specifics about where it would appear, etc. Assuming prosigns count as 1

**Comment by sclitheroe** [comment]
In my opinion, it could be tucked in below the timing data in the “eyeball box” up top, since that text box is the source of the calculated value.

In terms of parsing character count, I don’t think counting prosigns as 1 is strictly needed in the initial version – the goal is to let students mark their practice homework and determine their percent success rate so they know when to add characters/up speed/move on in their learning (or conversely, to not stick at a high success rate and push themselves) – so long as the number is consistent, even if its off by a couple it won’t matter statistically since the students are learning on a relatively large set of characters each practice – even 1 minute at 12/8 is 50+ chars.  Whatever the equivalent of strlen() is for that text entry box is plenty accurate for this purpose, prosigns or not.

73,
Scott
