### ISSUE TITLE
Issue with the Player after downloading to android phone

### ISSUE THREAD

**Issue by nolleto1** [LongIslandCW/morsebrowser#96]
Randy,
I downloaded the player to my phone and unzipped the files.  The bottom portion of the player seems to be OK but the top isn't.  I can't set any of the class lessons.  I'm using a Galaxy S6 and the latest version of chrome.
Tom AB5T
![Screenshot_20220602-112512](https://user-images.githubusercontent.com/103961372/171736223-d9bd3e51-b5fd-4c2b-8fca-ea65fcf083a2.png)
![Screenshot_20220602-112525](https://user-images.githubusercontent.com/103961372/171736225-df61336b-b8c7-44d8-87e8-a226c3d1de51.png)

**Comment by RandyLoeb** [comment]
@nolleto1 I just looked into this so I can take it with me on the plane. It was "broken" for me too but it is not us. Well it turns out that most android browsers no longer allow loading web pages with javascript locally, for some security reason I don't understand. Anyway, there is a solution, which is to run a tiny web server app on the phone. I used this one: https://play.google.com/store/apps/details?id=jp.ubi.common.http.server  and it seems to be working fine.  We can set up a call if you need help setting up, it took me two minutes.
